# src/dashboard.py
import os
import pandas as pd
import streamlit as st
import plotly.express as px
import snowflake.connector
from dotenv import load_dotenv

# Load Environment Variables
load_dotenv()

# Streamlit Page Configuration
st.set_page_config(
    page_title="StreamNexus Real-Time Operations",
    page_icon="🚕",
    layout="wide"
)

# Title & Infrastructure Context
st.title("🚕 StreamNexus Real-Time Operations Dashboard")
st.markdown("### **Telemetry Analysis Matrix: Kafka ──> Snowflake ──> Streamlit**")

# Auto-Refresh Control Panel Sidebar Component
st.sidebar.header("🔄 Stream Control Panel")
refresh_rate = st.sidebar.slider("Polling Frequency (Seconds)", min_value=2, max_value=30, value=5)
enable_refresh = st.sidebar.checkbox("Activate Live Stream", value=True)

# Connect to Snowflake
@st.cache_resource
def get_connection():
    return snowflake.connector.connect(
        user=os.getenv("SNOWFLAKE_USER"),
        password=os.getenv("SNOWFLAKE_PASSWORD"),
        account=os.getenv("SNOWFLAKE_ACCOUNT"),
        warehouse=os.getenv("SNOWFLAKE_WAREHOUSE"),
        database=os.getenv("SNOWFLAKE_DATABASE"),
        schema=os.getenv("SNOWFLAKE_SCHEMA")
    )

try:
    conn = get_connection()
except Exception as conn_err:
    st.error(f"Failed to securely authenticate with Snowflake: {conn_err}")
    st.stop()

# Load Data Matrix (Extracting Phase 5 Schema parameters)
query = """
SELECT 
    RIDE_ID, USER_ID, DRIVER_ID, LOCATION, AREA,
    BASE_DISTANCE_MILES, ESTIMATED_DURATION_MINUTES, TRAFFIC_DELAY_MULTIPLIER,
    SIMULATED_DEMAND_SCORE, SIMULATED_SUPPLY_SCORE, SURGE_MULTIPLIER,
    FARE, STATUS, TIMESTAMP
FROM rides
ORDER BY TIMESTAMP DESC
LIMIT 10000
"""

# Fetch DataFrame
try:
    df = pd.read_sql(query, conn)
    # Ensure Snowflake column names are handled cleanly
    df.columns = [col.upper() for col in df.columns]
except Exception as query_err:
    st.error(f"Error querying operational pipeline log store: {query_err}")
    st.stop()

if df.empty:
    st.warning("Data pipeline active, but target Snowflake table is currently empty.")
    if enable_refresh:
        st.rerun()
    st.stop()

# KPI METRIC SCORECARD GRIDS
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(label="Total Logged Telemetry Rows", value=f"{len(df):,}")

with col2:
    st.metric(label="Gross Realized Revenue", value=f"${df['FARE'].sum():,.2f}")

with col3:
    st.metric(label="Average Ticket Fare Price", value=f"${df['FARE'].mean():.2f}")

with col4:
    # Captures maximum value generated by your producer's calculate_surge module
    max_surge = df['SURGE_MULTIPLIER'].max()
    st.metric(
        label="Peak System Surge Factor", 
        value=f"{max_surge:.2f}x",
        delta="Market Peak" if max_surge > 1.0 else "Stable Market"
    )

st.markdown("---")

# --- ROW 1: SIMULATION INTELLIGENCE VISUALIZATIONS ---
chart_col1, chart_col2 = st.columns(2)

with chart_col1:
    st.subheader("📈 Dynamic Surge & Traffic Density Analysis")
    # Proves your Phase 5 surge-to-traffic logic is working under variable condition tracking
    fig_surge = px.scatter(
        df.head(1000), # Sample top 1000 records for responsive rendering
        x="TRAFFIC_DELAY_MULTIPLIER",
        y="SURGE_MULTIPLIER",
        color="LOCATION",
        size="FARE",
        hover_data=["AREA", "SIMULATED_DEMAND_SCORE", "SIMULATED_SUPPLY_SCORE"],
        title="Surge Pricing Multipliers vs. Traffic Congestion Vectors"
    )
    st.plotly_chart(fig_surge, use_container_width=True)

with chart_col2:
    st.subheader("🔄 Ride Lifecycle Status Progression")
    # Visualizes the four sequential lifecycle event states (SEARCHING -> EN_ROUTE)
    status_df = df.groupby("STATUS").size().reset_index(name="EVENT_COUNT")
    fig_status = px.pie(
        status_df, 
        values="EVENT_COUNT", 
        names="STATUS", 
        hole=0.4,
        title="Distribution of Pipeline State-Machine Milestones",
        color_discrete_sequence=px.colors.sequential.Sunsetdark
    )
    st.plotly_chart(fig_status, use_container_width=True)

# --- ROW 2: SPATIAL METRIC PROFILES ---
chart_col3, chart_col4 = st.columns(2)

with chart_col3:
    st.subheader("🌆 Ride Volume Distribution by Region")
    location_df = df.groupby("LOCATION").size().reset_index(name="TOTAL_RIDES").sort_values("TOTAL_RIDES", ascending=False)
    fig_loc = px.bar(
        location_df, 
        x="LOCATION", 
        y="TOTAL_RIDES", 
        color="LOCATION",
        title="Aggregate Active Booking Volume per Core City"
    )
    st.plotly_chart(fig_loc, use_container_width=True)

with chart_col4:
    st.subheader("📍 Hotspot Micro-Zone Analysis (Top 10)")
    area_df = df.groupby(["LOCATION", "AREA"]).size().reset_index(name="RIDES").sort_values("RIDES", ascending=False).head(10)
    fig_area = px.bar(
        area_df, 
        x="RIDES", 
        y="AREA", 
        color="LOCATION", 
        orientation="h",
        title="Highest Demand Neighborhood Microzones"
    )
    st.plotly_chart(fig_area, use_container_width=True)

# --- ROW 3: DETAILED RECORDS SUBSECTION ---
st.subheader("📋 Raw Live Stream Audit Log (Latest 25 Operational Pulses)")
st.dataframe(
    df.head(25),
    use_container_width=True,
    column_config={
        "RIDE_ID": "Ride Identifier",
        "USER_ID": "User ID",
        "DRIVER_ID": "Assigned Driver ID",
        "SURGE_MULTIPLIER": "Surge Factor",
        "FARE": "Total Paid ($)",
        "STATUS": "State Frame"
    }
)

# Automated Refresh Loop Execution block
if enable_refresh:
    import time
    time.sleep(refresh_rate)
    st.rerun()